<?php
declare(strict_types=1);

use Phinx\Migration\AbstractMigration;

final class AddSkus extends AbstractMigration
{
    /**
     * Change Method.
     *
     * Write your reversible migrations using this method.
     *
     * More information on writing migrations is available here:
     * https://book.cakephp.org/phinx/0/en/migrations.html#the-change-method
     *
     * Remember to call "create()" or "update()" and NOT "save()" when working
     * with the Table class.
     */
    public function change(): void
    {
        $skus = [
            [
                'id'          => 1,
                'description' => 'Customer Uses Own Fedex Account',
                'name'        => '1FEDEX_3RD_PARTY',
                'price'       => '{"amount":500,"currency":"USD"}',
                'taxable'     => 1,
                'created_at'  => '2019-06-23 02:55:31',
                'updated_at'  => null,
                'active'      => 0,
            ],
            [
                'id'          => 2,
                'description' => '1_MO_GOLD',
                'name'        => '1_MO_GOLD',
                'price'       => '{"amount":1899,"currency":"USD"}',
                'taxable'     => 1,
                'created_at'  => '2019-06-23 02:55:31',
                'updated_at'  => null,
                'active'      => 1,
            ],
            [
                'id'          => 3,
                'description' => '1_mo_Silver',
                'name'        => '1_MO_SILVER',
                'price'       => '{"amount":1599,"currency":"USD"}',
                'taxable'     => 1,
                'created_at'  => '2019-06-23 02:55:32',
                'updated_at'  => null,
                'active'      => 1,
            ],
            [
                'id'          => 4,
                'description' => '3-Month Gold Vacation Membership',
                'name'        => '3MO_GOLD',
                'price'       => '{"amount":5697,"currency":"USD"}',
                'taxable'     => 1,
                'created_at'  => '2019-06-23 02:55:32',
                'updated_at'  => null,
                'active'      => 0,
            ],
            [
                'id'          => 5,
                'description' => '3-Month Silver Vacation Membership',
                'name'        => '3MO_SILV',
                'price'       => '{"amount":4797,"currency":"USD"}',
                'taxable'     => 1,
                'created_at'  => '2019-06-23 02:55:32',
                'updated_at'  => null,
                'active'      => 0,
            ],
            [
                'id'          => 6,
                'description' => '6-Month Gold Vacation Membership',
                'name'        => '6MO_GOLD',
                'price'       => '{"amount":11394,"currency":"USD"}',
                'taxable'     => 1,
                'created_at'  => '2019-06-23 02:55:32',
                'updated_at'  => null,
                'active'      => 0,
            ],
            [
                'id'          => 7,
                'description' => '6-Month Silver Vacation Membership',
                'name'        => '6MO_SILV',
                'price'       => '{"amount":9594,"currency":"USD"}',
                'taxable'     => 1,
                'created_at'  => '2019-06-23 02:55:32',
                'updated_at'  => null,
                'active'      => 0,
            ],
            [
                'id'          => 8,
                'description' => 'Plan Extension',
                'name'        => 'ABNDN_01',
                'price'       => '{"amount":0,"currency":"USD"}',
                'taxable'     => 1,
                'created_at'  => '2019-06-23 02:55:32',
                'updated_at'  => null,
                'active'      => 1,
            ],
            [
                'id'          => 9,
                'description' => 'Rescinded Sales',
                'name'        => 'BADDEBT',
                'price'       => '{"amount":0,"currency":"USD"}',
                'taxable'     => 0,
                'created_at'  => '2019-06-23 02:55:33',
                'updated_at'  => null,
                'active'      => 1,
            ],
            [
                'id'          => 10,
                'description' => 'Bronze Membership',
                'name'        => 'BRON_01',
                'price'       => '{"amount":14999,"currency":"USD"}',
                'taxable'     => 1,
                'created_at'  => '2019-06-23 02:55:33',
                'updated_at'  => null,
                'active'      => 1,
            ],
            [
                'id'          => 11,
                'description' => 'Paid Cash On Behalf Of Member',
                'name'        => 'CASH_01',
                'price'       => '{"amount":0,"currency":"USD"}',
                'taxable'     => 0,
                'created_at'  => '2019-06-23 02:55:33',
                'updated_at'  => null,
                'active'      => 1,
            ],
            [
                'id'          => 12,
                'description' => 'Certified Mail Call',
                'name'        => 'CERT_01',
                'price'       => '{"amount":100,"currency":"USD"}',
                'taxable'     => 1,
                'created_at'  => '2019-06-23 02:55:33',
                'updated_at'  => null,
                'active'      => 1,
            ],
            [
                'id'          => 13,
                'description' => 'Collections Fee',
                'name'        => 'COLLFEE',
                'price'       => '{"amount":0,"currency":"USD"}',
                'taxable'     => 0,
                'created_at'  => '2019-06-23 02:55:33',
                'updated_at'  => null,
                'active'      => 1,
            ],
            [
                'id'          => 14,
                'description' => 'Comp\'d Account',
                'name'        => 'COMP_01',
                'price'       => '{"amount":0,"currency":"USD"}',
                'taxable'     => 0,
                'created_at'  => '2019-06-23 02:55:34',
                'updated_at'  => null,
                'active'      => 1,
            ],
            [
                'id'          => 15,
                'description' => 'Content_Scan',
                'name'        => 'CONTENT_SCAN',
                'price'       => '{"amount":250,"currency":"USD"}',
                'taxable'     => 1,
                'created_at'  => '2019-06-23 02:55:34',
                'updated_at'  => null,
                'active'      => 1,
            ],
            [
                'id'          => 16,
                'description' => 'Credit/Debit Card Convenience Fee',
                'name'        => 'CONV_01',
                'price'       => '{"amount":0,"currency":"USD"}',
                'taxable'     => 1,
                'created_at'  => '2019-06-23 02:55:34',
                'updated_at'  => null,
                'active'      => 1,
            ],
            [
                'id'          => 17,
                'description' => 'Unscheduled Mail Pick Up',
                'name'        => 'CPU_01',
                'price'       => '{"amount":100,"currency":"USD"}',
                'taxable'     => 1,
                'created_at'  => '2019-06-23 02:55:34',
                'updated_at'  => null,
                'active'      => 1,
            ],
            [
                'id'          => 18,
                'description' => 'Add\'l Pages Fax',
                'name'        => 'FAX_01',
                'price'       => '{"amount":100,"currency":"USD"}',
                'taxable'     => 1,
                'created_at'  => '2019-06-23 02:55:34',
                'updated_at'  => null,
                'active'      => 1,
            ],
            [
                'id'          => 19,
                'description' => 'First Page Fax',
                'name'        => 'FAX_02',
                'price'       => '{"amount":200,"currency":"USD"}',
                'taxable'     => 1,
                'created_at'  => '2019-06-23 02:55:35',
                'updated_at'  => null,
                'active'      => 1,
            ],
            [
                'id'          => 20,
                'description' => 'FedEx Priority Overnight',
                'name'        => 'FEDEX_1DAY_01',
                'price'       => '{"amount":110,"currency":"USD"}',
                'taxable'     => 1,
                'created_at'  => '2019-06-23 02:55:35',
                'updated_at'  => null,
                'active'      => 1,
            ],
            [
                'id'          => 21,
                'description' => 'FedEx Standard Overnight',
                'name'        => 'FEDEX_1DAY_02',
                'price'       => '{"amount":110,"currency":"USD"}',
                'taxable'     => 1,
                'created_at'  => '2019-06-23 02:55:35',
                'updated_at'  => null,
                'active'      => 1,
            ],
            [
                'id'          => 22,
                'description' => 'FedEx First Overnight',
                'name'        => 'FEDEX_1DAY_03',
                'price'       => '{"amount":110,"currency":"USD"}',
                'taxable'     => 1,
                'created_at'  => '2019-06-23 02:55:35',
                'updated_at'  => null,
                'active'      => 1,
            ],
            [
                'id'          => 23,
                'description' => 'FedEx 2 Day',
                'name'        => 'FEDEX_2DAY_01',
                'price'       => '{"amount":110,"currency":"USD"}',
                'taxable'     => 1,
                'created_at'  => '2019-06-23 02:55:35',
                'updated_at'  => null,
                'active'      => 1,
            ],
            [
                'id'          => 24,
                'description' => 'FedEx 3 Day',
                'name'        => 'FEDEX_3DAY_01',
                'price'       => '{"amount":110,"currency":"USD"}',
                'taxable'     => 1,
                'created_at'  => '2019-06-23 02:55:35',
                'updated_at'  => null,
                'active'      => 1,
            ],
            [
                'id'          => 25,
                'description' => 'Fedex Price Difference',
                'name'        => 'FEDEX_DIFF_01',
                'price'       => '{"amount":0,"currency":"USD"}',
                'taxable'     => 0,
                'created_at'  => '2019-06-23 02:55:36',
                'updated_at'  => null,
                'active'      => 1,
            ],
            [
                'id'          => 26,
                'description' => 'FedEx Ground',
                'name'        => 'FEDEX_GND_01',
                'price'       => '{"amount":110,"currency":"USD"}',
                'taxable'     => 1,
                'created_at'  => '2019-06-23 02:55:36',
                'updated_at'  => null,
                'active'      => 1,
            ],
            [
                'id'          => 27,
                'description' => 'FedEx International',
                'name'        => 'FEDEX_INT_01',
                'price'       => '{"amount":510,"currency":"USD"}',
                'taxable'     => 1,
                'created_at'  => '2019-06-23 02:55:36',
                'updated_at'  => null,
                'active'      => 1,
            ],
            [
                'id'          => 28,
                'description' => 'Gift Card',
                'name'        => 'GIFTCARD',
                'price'       => '{"amount":0,"currency":"USD"}',
                'taxable'     => 0,
                'created_at'  => '2019-06-23 02:55:37',
                'updated_at'  => null,
                'active'      => 1,
            ],
            [
                'id'          => 29,
                'description' => 'Gold Membership',
                'name'        => 'GOLD_01',
                'price'       => '{"amount":18999,"currency":"USD"}',
                'taxable'     => 1,
                'created_at'  => '2019-06-23 02:55:37',
                'updated_at'  => null,
                'active'      => 1,
            ],
            [
                'id'          => 30,
                'description' => 'Quarterly Gold Plan/Renewal',
                'name'        => 'GOLD_02',
                'price'       => '{"amount":5697,"currency":"USD"}',
                'taxable'     => 1,
                'created_at'  => '2019-06-23 02:55:37',
                'updated_at'  => null,
                'active'      => 1,
            ],
            [
                'id'          => 31,
                'description' => 'Add\'l Address Labels',
                'name'        => 'LAB_01',
                'price'       => '{"amount":100,"currency":"USD"}',
                'taxable'     => 1,
                'created_at'  => '2019-06-23 02:55:37',
                'updated_at'  => null,
                'active'      => 1,
            ],
            [
                'id'          => 32,
                'description' => 'Free Lunch',
                'name'        => 'LUN_01',
                'price'       => '{"amount":0,"currency":"USD"}',
                'taxable'     => 1,
                'created_at'  => '2019-06-23 02:55:37',
                'updated_at'  => null,
                'active'      => 1,
            ],
            [
                'id'          => 33,
                'description' => 'Perishable Medication Call',
                'name'        => 'MED_01',
                'price'       => '{"amount":100,"currency":"USD"}',
                'taxable'     => 1,
                'created_at'  => '2019-06-23 02:55:38',
                'updated_at'  => null,
                'active'      => 1,
            ],
            [
                'id'          => 34,
                'description' => 'Miscellaneous Charge',
                'name'        => 'MISCSKU',
                'price'       => '{"amount":0,"currency":"USD"}',
                'taxable'     => 1,
                'created_at'  => '2019-06-23 02:55:38',
                'updated_at'  => null,
                'active'      => 1,
            ],
            [
                'id'          => 35,
                'description' => 'New Bronze Account',
                'name'        => 'NEW_BRON_01',
                'price'       => '{"amount":14999,"currency":"USD"}',
                'taxable'     => 1,
                'created_at'  => '2019-06-23 02:55:40',
                'updated_at'  => null,
                'active'      => 1,
            ],
            [
                'id'          => 36,
                'description' => 'New Gold Account',
                'name'        => 'NEW_GOLD_01',
                'price'       => '{"amount":18999,"currency":"USD"}',
                'taxable'     => 1,
                'created_at'  => '2019-06-23 02:55:40',
                'updated_at'  => null,
                'active'      => 1,
            ],
            [
                'id'          => 37,
                'description' => 'New Platinum Account',
                'name'        => 'NEW_PLAT_01',
                'price'       => '{"amount":22999,"currency":"USD"}',
                'taxable'     => 1,
                'created_at'  => '2019-06-23 02:55:40',
                'updated_at'  => null,
                'active'      => 1,
            ],
            [
                'id'          => 38,
                'description' => 'New Silver Account',
                'name'        => 'NEW_SILV_01',
                'price'       => '{"amount":16999,"currency":"USD"}',
                'taxable'     => 1,
                'created_at'  => '2019-06-23 02:55:40',
                'updated_at'  => null,
                'active'      => 1,
            ],
            [
                'id'          => 39,
                'description' => 'Notary Fee',
                'name'        => 'NOT_01',
                'price'       => '{"amount":800,"currency":"USD"}',
                'taxable'     => 1,
                'created_at'  => '2019-06-23 02:55:40',
                'updated_at'  => null,
                'active'      => 1,
            ],
            [
                'id'          => 40,
                'description' => 'Returned Check Fee',
                'name'        => 'NSF_FEE',
                'price'       => '{"amount":3500,"currency":"USD"}',
                'taxable'     => 0,
                'created_at'  => '2019-06-23 02:55:41',
                'updated_at'  => null,
                'active'      => 1,
            ],
            [
                'id'          => 41,
                'description' => 'FOR POSTAGE DUE',
                'name'        => 'PDUE_01',
                'price'       => '{"amount":0,"currency":"USD"}',
                'taxable'     => 0,
                'created_at'  => '2019-06-23 02:55:41',
                'updated_at'  => null,
                'active'      => 1,
            ],
            [
                'id'          => 42,
                'description' => 'Oversized Package',
                'name'        => 'PKG_01',
                'price'       => '{"amount":100,"currency":"USD"}',
                'taxable'     => 1,
                'created_at'  => '2019-06-23 02:55:41',
                'updated_at'  => null,
                'active'      => 1,
            ],
            [
                'id'          => 43,
                'description' => 'Oversized Package',
                'name'        => 'PKG_02',
                'price'       => '{"amount":200,"currency":"USD"}',
                'taxable'     => 1,
                'created_at'  => '2019-06-23 02:55:42',
                'updated_at'  => null,
                'active'      => 1,
            ],
            [
                'id'          => 44,
                'description' => 'Oversized Package',
                'name'        => 'PKG_03',
                'price'       => '{"amount":300,"currency":"USD"}',
                'taxable'     => 1,
                'created_at'  => '2019-06-23 02:55:43',
                'updated_at'  => null,
                'active'      => 1,
            ],
            [
                'id'          => 45,
                'description' => 'Oversized Package',
                'name'        => 'PKG_MISC',
                'price'       => '{"amount":0,"currency":"USD"}',
                'taxable'     => 1,
                'created_at'  => '2019-06-23 02:55:43',
                'updated_at'  => null,
                'active'      => 1,
            ],
            [
                'id'          => 46,
                'description' => 'Platinum Membership',
                'name'        => 'PLAT_01',
                'price'       => '{"amount":22999,"currency":"USD"}',
                'taxable'     => 1,
                'created_at'  => '2019-06-23 02:55:44',
                'updated_at'  => null,
                'active'      => 1,
            ],
            [
                'id'          => 47,
                'description' => 'Prorate To 1st Of Following Month',
                'name'        => 'PRORATE_01',
                'price'       => '{"amount":0,"currency":"USD"}',
                'taxable'     => 1,
                'created_at'  => '2019-06-23 02:55:44',
                'updated_at'  => null,
                'active'      => 1,
            ],
            [
                'id'          => 48,
                'description' => 'Quarterly Titanium Plus',
                'name'        => 'QTLY_TITAN_PLUS',
                'price'       => '{"amount":7797,"currency":"USD"}',
                'taxable'     => 1,
                'created_at'  => '2019-06-23 02:55:44',
                'updated_at'  => null,
                'active'      => 1,
            ],
            [
                'id'          => 49,
                'description' => 'Reactivation Fee',
                'name'        => 'REACT_01',
                'price'       => '{"amount":1500,"currency":"USD"}',
                'taxable'     => 1,
                'created_at'  => '2019-06-23 02:55:44',
                'updated_at'  => null,
                'active'      => 1,
            ],
            [
                'id'          => 50,
                'description' => 'Postage Refund Closed Account',
                'name'        => 'REFUND_01',
                'price'       => '{"amount":0,"currency":"USD"}',
                'taxable'     => 0,
                'created_at'  => '2019-06-23 02:55:45',
                'updated_at'  => null,
                'active'      => 1,
            ],
            [
                'id'          => 51,
                'description' => 'Miscellaneous Refund',
                'name'        => 'REFUND_02',
                'price'       => '{"amount":0,"currency":"USD"}',
                'taxable'     => 0,
                'created_at'  => '2019-06-23 02:55:49',
                'updated_at'  => null,
                'active'      => 1,
            ],
            [
                'id'          => 52,
                'description' => 'Basic Vehicle Checklist Processing',
                'name'        => 'REG_01',
                'price'       => '{"amount":2499,"currency":"USD"}',
                'taxable'     => 1,
                'created_at'  => '2019-06-23 02:55:51',
                'updated_at'  => null,
                'active'      => 1,
            ],
            [
                'id'          => 53,
                'description' => 'Basic Vehicle Registration Completed',
                'name'        => 'REG_02',
                'price'       => '{"amount":2000,"currency":"USD"}',
                'taxable'     => 1,
                'created_at'  => '2019-06-23 02:55:51',
                'updated_at'  => null,
                'active'      => 1,
            ],
            [
                'id'          => 54,
                'description' => 'Trust Vehicle Registration',
                'name'        => 'REG_04',
                'price'       => '{"amount":3499,"currency":"USD"}',
                'taxable'     => 1,
                'created_at'  => '2019-06-23 02:55:51',
                'updated_at'  => null,
                'active'      => 1,
            ],
            [
                'id'          => 55,
                'description' => 'Registered Agent Service',
                'name'        => 'REG_AGT',
                'price'       => '{"amount":4000,"currency":"USD"}',
                'taxable'     => 1,
                'created_at'  => '2019-06-23 02:55:51',
                'updated_at'  => null,
                'active'      => 1,
            ],
            [
                'id'          => 56,
                'description' => 'Vehicle Registration Check Fee',
                'name'        => 'REG_CHECKFEE',
                'price'       => '{"amount":250,"currency":"USD"}',
                'taxable'     => 1,
                'created_at'  => '2019-06-23 02:55:51',
                'updated_at'  => null,
                'active'      => 1,
            ],
            [
                'id'          => 57,
                'description' => 'Lease/Import Vehicle Registration',
                'name'        => 'REG_LEASE_01',
                'price'       => '{"amount":5000,"currency":"USD"}',
                'taxable'     => 1,
                'created_at'  => '2019-06-23 02:55:51',
                'updated_at'  => null,
                'active'      => 1,
            ],
            [
                'id'          => 58,
                'description' => 'Vehicle Renewal',
                'name'        => 'REN_01',
                'price'       => '{"amount":1000,"currency":"USD"}',
                'taxable'     => 1,
                'created_at'  => '2019-06-23 02:55:52',
                'updated_at'  => null,
                'active'      => 1,
            ],
            [
                'id'          => 59,
                'description' => 'Rewards Membership Enrollment',
                'name'        => 'REWARDS',
                'price'       => '{"amount":0,"currency":"USD"}',
                'taxable'     => 0,
                'created_at'  => '2019-06-23 02:55:52',
                'updated_at'  => null,
                'active'      => 1,
            ],
            [
                'id'          => 60,
                'description' => 'SCAN_OLD_MAIL',
                'name'        => 'SCAN_OLD_MAIL',
                'price'       => '{"amount":25,"currency":"USD"}',
                'taxable'     => 1,
                'created_at'  => '2019-06-23 02:55:52',
                'updated_at'  => null,
                'active'      => 1,
            ],
            [
                'id'          => 61,
                'description' => 'Silver Membership',
                'name'        => 'SILV_01',
                'price'       => '{"amount":16999,"currency":"USD"}',
                'taxable'     => 1,
                'created_at'  => '2019-06-23 02:55:52',
                'updated_at'  => null,
                'active'      => 1,
            ],
            [
                'id'          => 62,
                'description' => 'Quarterly Silver Plan/Renewal',
                'name'        => 'SILV_02',
                'price'       => '{"amount":4797,"currency":"USD"}',
                'taxable'     => 1,
                'created_at'  => '2019-06-23 02:55:52',
                'updated_at'  => null,
                'active'      => 1,
            ],
            [
                'id'          => 63,
                'description' => 'Employee Stamp Purchase',
                'name'        => 'STAFF-PDUE',
                'price'       => '{"amount":0,"currency":"USD"}',
                'taxable'     => 0,
                'created_at'  => '2019-06-23 02:55:53',
                'updated_at'  => null,
                'active'      => 1,
            ],
            [
                'id'          => 64,
                'description' => 'Application/Startup Fee',
                'name'        => 'START_01',
                'price'       => '{"amount":2500,"currency":"USD"}',
                'taxable'     => 1,
                'created_at'  => '2019-06-23 02:55:54',
                'updated_at'  => null,
                'active'      => 1,
            ],
            [
                'id'          => 65,
                'description' => 'Scan_7piece',
                'name'        => 'TITANIUM',
                'price'       => '{"amount":17999,"currency":"USD"}',
                'taxable'     => 1,
                'created_at'  => '2019-06-23 02:55:55',
                'updated_at'  => null,
                'active'      => 0,
            ],
            [
                'id'          => 66,
                'description' => 'Titanium Plus',
                'name'        => 'TITANIUM_PLUS',
                'price'       => '{"amount":22899,"currency":"USD"}',
                'taxable'     => 1,
                'created_at'  => '2019-06-23 02:55:55',
                'updated_at'  => null,
                'active'      => 1,
            ],
            [
                'id'          => 67,
                'description' => 'Upgrade Current Plan',
                'name'        => 'UPGR_01',
                'price'       => '{"amount":0,"currency":"USD"}',
                'taxable'     => 1,
                'created_at'  => '2019-06-23 02:55:55',
                'updated_at'  => null,
                'active'      => 1,
            ],
            [
                'id'          => 68,
                'description' => 'First-Class, Flats',
                'name'        => 'USPS_1ST_FLATS',
                'price'       => '{"amount":135,"currency":"USD"}',
                'taxable'     => 1,
                'created_at'  => '2019-06-23 02:55:55',
                'updated_at'  => null,
                'active'      => 1,
            ],
            [
                'id'          => 69,
                'description' => 'First-Class, Flats with tracking',
                'name'        => 'USPS_1ST_FLATS2',
                'price'       => '{"amount":135,"currency":"USD"}',
                'taxable'     => 1,
                'created_at'  => '2019-06-23 02:55:55',
                'updated_at'  => null,
                'active'      => 1,
            ],
            [
                'id'          => 70,
                'description' => 'USPS First-Class International, Flats',
                'name'        => 'USPS_1ST_INT_01',
                'price'       => '{"amount":510,"currency":"USD"}',
                'taxable'     => 1,
                'created_at'  => '2019-06-23 02:55:55',
                'updated_at'  => null,
                'active'      => 1,
            ],
            [
                'id'          => 71,
                'description' => 'USPS Priority Mail Express',
                'name'        => 'USPS_2DAY_01',
                'price'       => '{"amount":110,"currency":"USD"}',
                'taxable'     => 1,
                'created_at'  => '2019-06-23 02:55:55',
                'updated_at'  => null,
                'active'      => 1,
            ],
            [
                'id'          => 72,
                'description' => 'USPS Priority Mail Express, Envelope',
                'name'        => 'USPS_2DAY_02',
                'price'       => '{"amount":110,"currency":"USD"}',
                'taxable'     => 1,
                'created_at'  => '2019-06-23 02:55:55',
                'updated_at'  => null,
                'active'      => 1,
            ],
            [
                'id'          => 73,
                'description' => 'Priority Mail Express Mail Parcel',
                'name'        => 'USPS_2DAY_03',
                'price'       => '{"amount":110,"currency":"USD"}',
                'taxable'     => 1,
                'created_at'  => '2019-06-23 02:55:56',
                'updated_at'  => null,
                'active'      => 1,
            ],
            [
                'id'          => 74,
                'description' => 'Postage and Services',
                'name'        => 'POSTAGE_&_SERV_FUND',
                'price'       => '{"amount":0,"currency":"USD"}',
                'taxable'     => 0,
                'created_at'  => '2019-08-22 14:16:22',
                'updated_at'  => null,
                'active'      => 1,
            ],
            [
                'id'          => 75,
                'description' => 'USPS International',
                'name'        => 'USPS_INT_01',
                'price'       => '{"amount":510,"currency":"USD"}',
                'taxable'     => 1,
                'created_at'  => '2019-09-30 08:11:37',
                'updated_at'  => null,
                'active'      => 1,
            ],
            [
                'id'          => 76,
                'description' => 'USPS International Flat Rate Envelope',
                'name'        => 'USPS_INT_02',
                'price'       => '{"amount":510,"currency":"USD"}',
                'taxable'     => 1,
                'created_at'  => '2019-09-30 08:11:40',
                'updated_at'  => null,
                'active'      => 1,
            ],
            [
                'id'          => 77,
                'description' => 'USPS International Flat Rate Medium Box',
                'name'        => 'USPS_INT_03',
                'price'       => '{"amount":510,"currency":"USD"}',
                'taxable'     => 1,
                'created_at'  => '2019-09-30 08:11:41',
                'updated_at'  => null,
                'active'      => 1,
            ],
            [
                'id'          => 78,
                'description' => 'USPS International Flat Rate Large Box',
                'name'        => 'USPS_INT_04',
                'price'       => '{"amount":510,"currency":"USD"}',
                'taxable'     => 1,
                'created_at'  => '2019-09-30 08:11:43',
                'updated_at'  => null,
                'active'      => 1,
            ],
            [
                'id'          => 79,
                'description' => 'USPS Priority',
                'name'        => 'USPS_PRI01',
                'price'       => '{"amount":110,"currency":"USD"}',
                'taxable'     => 1,
                'created_at'  => '2019-09-30 08:11:45',
                'updated_at'  => null,
                'active'      => 1,
            ],
            [
                'id'          => 80,
                'description' => 'USPS Priority Medium, FRB',
                'name'        => 'USPS_PRI02',
                'price'       => '{"amount":110,"currency":"USD"}',
                'taxable'     => 1,
                'created_at'  => '2019-09-30 08:11:47',
                'updated_at'  => null,
                'active'      => 1,
            ],
            [
                'id'          => 81,
                'description' => 'USPS Priority Large',
                'name'        => 'USPS_PRI03',
                'price'       => '{"amount":110,"currency":"USD"}',
                'taxable'     => 1,
                'created_at'  => '2019-09-30 08:11:48',
                'updated_at'  => null,
                'active'      => 1,
            ],
            [
                'id'          => 82,
                'description' => 'USPS Priority Small',
                'name'        => 'USPS_PRI04',
                'price'       => '{"amount":110,"currency":"USD"}',
                'taxable'     => 1,
                'created_at'  => '2019-09-30 08:11:49',
                'updated_at'  => null,
                'active'      => 1,
            ],
            [
                'id'          => 83,
                'description' => 'USPS Priority Flat Rate Envelope',
                'name'        => 'USPS_PRI05',
                'price'       => '{"amount":110,"currency":"USD"}',
                'taxable'     => 1,
                'created_at'  => '2019-09-30 08:11:51',
                'updated_at'  => null,
                'active'      => 1,
            ],
            [
                'id'          => 84,
                'description' => 'USPS Postcard',
                'name'        => 'USPS_POSTC_01',
                'price'       => '{"amount":144,"currency":"USD"}',
                'taxable'     => 1,
                'created_at'  => '2019-09-30 08:11:53',
                'updated_at'  => null,
                'active'      => 1,
            ],
            [
                'id'          => 85,
                'description' => 'New Titanium Plus',
                'name'        => 'NEW_TIT_PLUS_01',
                'price'       => '{"amount":22899,"currency":"USD"}',
                'taxable'     => 1,
                'created_at'  => '2019-10-18 18:36:46',
                'updated_at'  => null,
                'active'      => 1,
            ],
            [
                'id'          => 86,
                'description' => 'New Titanium Plus Quarterly',
                'name'        => 'NEW_TIT_QTLY_01',
                'price'       => '{"amount":7797,"currency":"USD"}',
                'taxable'     => 1,
                'created_at'  => '2019-10-18 23:11:40',
                'updated_at'  => null,
                'active'      => 1,
            ],
            [
                'id'          => 87,
                'description' => 'Vehicle Trouble Letter',
                'name'        => 'VEH_01',
                'price'       => '{"amount":500,"currency":"USD"}',
                'taxable'     => 1,
                'created_at'  => '2019-11-11 04:04:51',
                'updated_at'  => null,
                'active'      => 1,
            ],
            [
                'id'          => 88,
                'description' => 'Vehicle Title Request',
                'name'        => 'VEH_02',
                'price'       => '{"amount":1000,"currency":"USD"}',
                'taxable'     => 1,
                'created_at'  => '2019-11-11 04:04:51',
                'updated_at'  => null,
                'active'      => 1,
            ],
            [
                'id'          => 89,
                'description' => 'Vehicle Dealer Tax Affidavit',
                'name'        => 'VEH_03',
                'price'       => '{"amount":500,"currency":"USD"}',
                'taxable'     => 1,
                'created_at'  => '2019-11-11 04:04:51',
                'updated_at'  => null,
                'active'      => 1,
            ],
            [
                'id'          => 90,
                'description' => 'Vehicle Add\'l Trip',
                'name'        => 'VEH_04',
                'price'       => '{"amount":2500,"currency":"USD"}',
                'taxable'     => 1,
                'created_at'  => '2019-11-11 04:04:51',
                'updated_at'  => null,
                'active'      => 1,
            ],
            [
                'id'          => 91,
                'description' => 'Vehicle Rush Service',
                'name'        => 'VEH_05',
                'price'       => '{"amount":4000,"currency":"USD"}',
                'taxable'     => 1,
                'created_at'  => '2019-11-11 04:04:51',
                'updated_at'  => null,
                'active'      => 1,
            ],
            [
                'id'          => 92,
                'description' => 'Report Of Sale',
                'name'        => 'VEH_06',
                'price'       => '{"amount":1000,"currency":"USD"}',
                'taxable'     => 1,
                'created_at'  => '2019-11-11 04:04:51',
                'updated_at'  => null,
                'active'      => 1,
            ],
            [
                'id'          => 93,
                'description' => 'Handicapped Placards',
                'name'        => 'VEH_07',
                'price'       => '{"amount":1000,"currency":"USD"}',
                'taxable'     => 1,
                'created_at'  => '2019-11-11 04:04:51',
                'updated_at'  => null,
                'active'      => 1,
            ],
            [
                'id'          => 94,
                'description' => 'Lost Plates',
                'name'        => 'VEH_08',
                'price'       => '{"amount":1000,"currency":"USD"}',
                'taxable'     => 1,
                'created_at'  => '2019-11-11 04:04:51',
                'updated_at'  => null,
                'active'      => 1,
            ],
            [
                'id'          => 95,
                'description' => 'Specialized Plates',
                'name'        => 'VEH_09',
                'price'       => '{"amount":1000,"currency":"USD"}',
                'taxable'     => 1,
                'created_at'  => '2019-11-11 04:04:51',
                'updated_at'  => null,
                'active'      => 1,
            ],
            [
                'id'          => 96,
                'description' => 'Lien Release',
                'name'        => 'VEH_10',
                'price'       => '{"amount":1000,"currency":"USD"}',
                'taxable'     => 1,
                'created_at'  => '2019-11-11 04:04:51',
                'updated_at'  => null,
                'active'      => 1,
            ],
            [
                'id'          => 97,
                'description' => 'Vehicle Miscellaneous Charge',
                'name'        => 'VEH_MISC',
                'price'       => '{"amount": 0,"currency":"USD"}',
                'taxable'     => 1,
                'created_at'  => '2019-11-11 04:04:51',
                'updated_at'  => null,
                'active'      => 1,
            ],
            [
                'id'          => 98,
                'description' => 'Silver 6 month membership',
                'name'        => 'SILV_03',
                'price'       => '{"amount":8499,"currency":"USD"}',
                'taxable'     => 1,
                'created_at'  => '2019-11-13 09:19:15',
                'updated_at'  => null,
                'active'      => 1,
            ],
            [
                'id'          => 99,
                'description' => 'Gold 6 month membership',
                'name'        => 'GOLD_03',
                'price'       => '{"amount":9499,"currency":"USD"}',
                'taxable'     => 1,
                'created_at'  => '2019-11-13 09:19:15',
                'updated_at'  => null,
                'active'      => 1,
            ],
            [
                'id'          => 100,
                'description' => 'Titanium 6 month membership',
                'name'        => 'TITANIUM_PLUS_03',
                'price'       => '{"amount":11449,"currency":"USD"}',
                'taxable'     => 1,
                'created_at'  => '2019-11-13 09:19:15',
                'updated_at'  => null,
                'active'      => 1,
            ],
            [
                'id'          => 101,
                'description' => 'Vehicle Title Request',
                'name'        => 'VEH2_02',
                'price'       => '{"amount":500,"currency":"USD"}',
                'taxable'     => 1,
                'created_at'  => '2019-11-11 04:04:51',
                'updated_at'  => null,
                'active'      => 1,
            ],
            [
                'id'          => 102,
                'description' => 'Basic Vehicle Registration Completed',
                'name'        => 'REG2_02',
                'price'       => '{"amount":1500,"currency":"USD"}',
                'taxable'     => 1,
                'created_at'  => '2019-06-23 02:55:51',
                'updated_at'  => null,
                'active'      => 1,
            ],
            [
                'id'          => 103,
                'description' => 'Basic Vehicle Checklist Processing',
                'name'        => 'REG2_01',
                'price'       => '{"amount":1500,"currency":"USD"}',
                'taxable'     => 1,
                'created_at'  => '2019-06-23 02:55:51',
                'updated_at'  => null,
                'active'      => 1,
            ],
            [
                'id'          => 104,
                'description' => 'Short Term Titanium Plus',
                'name'        => 'ST_TIT_PLUS',
                'price'       => '{"amount":7797,"currency":"USD"}',
                'taxable'     => 1,
                'created_at'  => '2020-02-28 23:59:49',
                'updated_at'  => null,
                'active'      => 1,
            ],
            [
                'id'          => 105,
                'description' => 'Freight Handling',
                'name'        => 'FREIGHT',
                'price'       => '{"amount": 0,"currency":"USD"}',
                'taxable'     => 1,
                'created_at'  => '2020-03-01 02:22:50',
                'updated_at'  => null,
                'active'      => 1,
            ],
            [
                'id'          => 106,
                'description' => 'Balance Adjustment',
                'name'        => 'ADJUST',
                'price'       => '{"amount": 0,"currency":"USD"}',
                'taxable'     => 0,
                'created_at'  => '2020-03-02 03:08:58',
                'updated_at'  => null,
                'active'      => 1,
            ],
            [
                'id'          => 107,
                'description' => 'Vehicle Registration Processing Lease/Import',
                'name'        => 'REG_05',
                'price'       => '{"amount": 4500,"currency":"USD"}',
                'taxable'     => 0,
                'created_at'  => '2020-03-05 06:43:55',
                'updated_at'  => null,
                'active'      => 1,
            ],
        ];
        $this->table('products')->insert($skus)->save();
    }
}
